### ISSUE TITLE
Add survival analysis support

### ISSUE THREAD

**Issue by nick-robo** [SydneyBioX/Statial#5]
1. Make output play well with spicyR's survival analysis functionality.
2. Give alternate association value in a SpatialExeriement.
3. Document new functionality in vignette.

**Comment by fame2827** [comment]
Added to spicyR and made compatible with Kontextual: https://github.com/SydneyBioX/spicyR/commit/8d3cd8ccdc74a0177b2c32f94feaf61f4f8ff12d
