### ISSUE TITLE
calcStateChanges breaks when imageID argument is specified

### ISSUE THREAD

**Issue by fame2827** [SydneyBioX/Statial#9]
If I define the `imageID` argument in `calcStateChanges` it breaks the `dplyr::group_by`. Im pretty sure its because dplyr is trying to find the column `imageID` in the dataset rather that the string its assigned to which here is `ImageNumber` . If thats the case it should be an easy fix just use `!!sym(imageID)` in the group_by, which tells group_by to treat `imageID` as a variable rather than a column name.
![screenshot_2024-12-05_at_11 32 33___am](https://github.com/user-attachments/assets/1afa41bf-3173-477c-8c19-f72413c55efd)

**Comment by alexrunqin** [comment]
The latest commit should fix this
